"""
This type stub file was generated by pyright.
"""

from .async_ import *
from .sync import *

"""
discord.webhook
~~~~~~~~~~~~~~

Webhook support

:copyright: (c) 2015-present Rapptz
:license: MIT, see LICENSE for more details.

"""
