name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "/root/bot"

    - name: Executing remote command
      env:
        TOKEN: ${{ secrets.TOKEN }}
        DB_URL: ${{ secrets.DB_URL }}
        TENOR_API_KEY: ${{ secrets.TENOR_API_KEY }}
        OSU_API_KEY: ${{ secrets.OSU_API_KEY }}
        SAUCENAO_API_KEY: ${{ secrets.SAUCENAO_API_KEY }}
        IMGUR_ID: ${{ secrets.IMGUR_ID }}
        IMGUR_CLIENT: ${{ secrets.IMGUR_CLIENT }}
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        envs: TOKEN,DB_URL,TENOR_API_KEY,OSU_API_KEY,SAUCENAO_API_KEY,IMGUR_ID,IMGUR_CLIENT
        script: docker stop beako-run && docker build -t beako ./bot && docker run -d -it --rm --name beako-run beako && docker system prune -af